### ISSUE TITLE
Doesn’t work on iOS 14.3

### ISSUE THREAD

**Issue by jeasimon** [aabosh/Safari-In-Messages#2]
Looks like it doesn’t work k on iOS 14.3 (iPhone X with Taurine).

**Comment by aabosh** [comment]
Hi there,

Sorry for the delayed response!

I just made a change that should hopefully fix the tweak on iOS 14.

I've attached a `.zip` file that contains a `.deb` package with the fix. Would you be able to test it and verify?
[com.andrewabosh.safari-in-messages_1.0.1-2+debug_iphoneos-arm.deb.zip](https://github.com/aabosh/Safari-In-Messages/files/6328522/com.andrewabosh.safari-in-messages_1.0.1-2%2Bdebug_iphoneos-arm.deb.zip)

Thank you,
Andrew

**Comment by jeasimon** [comment]
Hello Andrew,

Just tested right now and I can confirm, it works like a charm!

Thank you again for your time, it’s really appreciate.

You rock !

Jean-Simon,
(iPhone X, Tautine, 14.4)

Envoyé de mon iPhone

Le 16 avr. 2021 à 22:45, Andrew Abosh ***@***.***> a écrit :

﻿

Hi there,

Sorry for the delayed response!

I just made a change that should hopefully fix the tweak on iOS 14.

I've attached a .zip file that contains a .deb package with the fix. Would you be able to test it and verify?
com.andrewabosh.safari-in-messages_1.0.1-2+debug_iphoneos-arm.deb.zip<https://github.com/aabosh/Safari-In-Messages/files/6328522/com.andrewabosh.safari-in-messages_1.0.1-2%2Bdebug_iphoneos-arm.deb.zip>

Thank you,
Andrew

**Comment by aabosh** [comment]
Great, happy to hear! Thanks for testing.

I'll push the new build to Chariz.
